# Generated by Django 2.2.9 on 2022-11-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221102_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create', to='posts.Group', verbose_name='Группа')),
            ],
        ),
    ]
