# Generated by Django 2.2.9 on 2022-11-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_create_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_post',
        ),
    ]
